name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      major_version:
        type: number
      minor_version:
        type: number
      patch_version:
        type: number
      name:
        type: string

jobs:
  call-release-trigger:
    # TODO reference proper action
    uses: ynput/ci-testing/.github/workflows/release_on_demand.yml@develop
    with:
      major: ${{ inputs.major_version }}
      minor: ${{ inputs.minor_version }}
      patch: ${{ inputs.patch_version }}
      name: ${{ inputs.name }}

    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      user: ${{ secrets.CI_USER }}
      email: ${{ secrets.CI_EMAIL }}
