name: Release Trigger

on:
  workflow_dispatch:

jobs:
  call-release-trigger:
    uses: ynput/ci-testing/.github/workflows/release_on_demand.yml@develop
    secrets:
      token: ${{ secrets.GH_TOKEN }}
      user: ${{ secrets.GH_USER }}
      email: ${{ secrets.GH_EMAIL }}
