name: Release Trigger

on:
  workflow_dispatch:

jobs:
  call-release-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Run release trigger
        uses: ynput/ci-testing/.github/workflows/release_on_demand.yml@develop
